default: &DEFAULT
  num_epochs: 1000
  batch_size: 256

FCNN1:
  <<: *DEFAULT
  model_name: fcnn1
  data_dir: "Data" # https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification
  checkpoint_dir: "checkpoints"
  log_dir: 'logs/fcnn1'
  gpu_vis_dev: '0'
  optimizer: "adam"
  num_epochs: 70
  batch_size: 128

FCNN2:
  <<: *DEFAULT
  model_name: fcnn2
  data_dir: "Data" # https://www.kaggle.com/datasets/andradaolteanu/gtzan-dataset-music-genre-classification
  checkpoint_dir: "checkpoints"
  log_dir: 'logs/fcnn2'
  gpu_vis_dev: '0'
  optimizer: "rmsprop"
  num_epochs: 500
  batch_size: 128

CNN1:
  <<: *DEFAULT
  model_name: cnn1
  data_dir: "Data"
  checkpoint_dir: "checkpoints"
  log_dir: 'logs/cnn1'
  gpu_vis_dev: '0'
  num_epochs: 30
  batch_size: 32
  lr: 0.0001
